name: Build Flet Android App
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet CLI Dependencies
        run: |
          pip install --upgrade pip
          pip install flet flet-runtime

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter Engine (Flet Exact Version)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'

      - name: Run Build Package
        run: |
          # --debug फ्लॅगमुळे ॲप क्रॅश न होता एरर थेट स्क्रीनवर दाखवेल
          echo "y" | flet build apk --debug

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Simple-Ledger-Android-APK
          path: build/apk/*.apk
